// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserMetadata is the predicate function for usermetadata builders.
type UserMetadata func(*sql.Selector)
