// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "amount", Type: field.TypeInt64, Default: 0},
		{Name: "currency_type", Type: field.TypeEnum, Enums: []string{"RUB", "USD", "EUR"}},
		{Name: "frozen", Type: field.TypeBool, Default: false},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_users_accounts",
				Columns:    []*schema.Column{AccountsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "disabled", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserMetadataColumns holds the columns for the "user_metadata" table.
	UserMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString},
		{Name: "gender", Type: field.TypeBool},
		{Name: "user_id", Type: field.TypeInt64, Unique: true},
	}
	// UserMetadataTable holds the schema information for the "user_metadata" table.
	UserMetadataTable = &schema.Table{
		Name:       "user_metadata",
		Columns:    UserMetadataColumns,
		PrimaryKey: []*schema.Column{UserMetadataColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_metadata_users_metadata",
				Columns:    []*schema.Column{UserMetadataColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		UsersTable,
		UserMetadataTable,
	}
)

func init() {
	AccountsTable.ForeignKeys[0].RefTable = UsersTable
	UserMetadataTable.ForeignKeys[0].RefTable = UsersTable
}
