// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: auth/v1/errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceErrors int32

const (
	ServiceErrors_USER_NOT_FOUND      ServiceErrors = 0
	ServiceErrors_USER_ALREADY_EXISTS ServiceErrors = 1
	ServiceErrors_WRONG_PASSWORD      ServiceErrors = 2
	ServiceErrors_INVALID_TOKEN       ServiceErrors = 3
)

// Enum value maps for ServiceErrors.
var (
	ServiceErrors_name = map[int32]string{
		0: "USER_NOT_FOUND",
		1: "USER_ALREADY_EXISTS",
		2: "WRONG_PASSWORD",
		3: "INVALID_TOKEN",
	}
	ServiceErrors_value = map[string]int32{
		"USER_NOT_FOUND":      0,
		"USER_ALREADY_EXISTS": 1,
		"WRONG_PASSWORD":      2,
		"INVALID_TOKEN":       3,
	}
)

func (x ServiceErrors) Enum() *ServiceErrors {
	p := new(ServiceErrors)
	*p = x
	return p
}

func (x ServiceErrors) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceErrors) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ServiceErrors) Type() protoreflect.EnumType {
	return &file_auth_v1_errors_proto_enumTypes[0]
}

func (x ServiceErrors) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceErrors.Descriptor instead.
func (ServiceErrors) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_auth_v1_errors_proto protoreflect.FileDescriptor

var file_auth_v1_errors_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x76, 0x31, 0x2a,
	0x63, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55,
	0x4e, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x41, 0x4c, 0x52,
	0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x57, 0x52, 0x4f, 0x4e, 0x47, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10,
	0x02, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x54, 0x4f, 0x4b,
	0x45, 0x4e, 0x10, 0x03, 0x42, 0x15, 0x5a, 0x13, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_auth_v1_errors_proto_rawDescOnce sync.Once
	file_auth_v1_errors_proto_rawDescData = file_auth_v1_errors_proto_rawDesc
)

func file_auth_v1_errors_proto_rawDescGZIP() []byte {
	file_auth_v1_errors_proto_rawDescOnce.Do(func() {
		file_auth_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth_v1_errors_proto_rawDescData)
	})
	return file_auth_v1_errors_proto_rawDescData
}

var file_auth_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_auth_v1_errors_proto_goTypes = []interface{}{
	(ServiceErrors)(0), // 0: auth.v1.ServiceErrors
}
var file_auth_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_errors_proto_init() }
func file_auth_v1_errors_proto_init() {
	if File_auth_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth_v1_errors_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_v1_errors_proto_goTypes,
		DependencyIndexes: file_auth_v1_errors_proto_depIdxs,
		EnumInfos:         file_auth_v1_errors_proto_enumTypes,
	}.Build()
	File_auth_v1_errors_proto = out.File
	file_auth_v1_errors_proto_rawDesc = nil
	file_auth_v1_errors_proto_goTypes = nil
	file_auth_v1_errors_proto_depIdxs = nil
}
